import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './GlobalRedux/provider'
import { useContext } from 'react'
import Navbar from '@/components/global-components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="pl">
      <body className={inter.className}> <Providers><Navbar/><div className="container pt-28"> {children} </div></Providers> </body>
    </html>

  )
}

{/* <div id="portal"></div> */}