import "./globals.css";
import { Providers } from "./GlobalRedux/provider";
import Navbar from "@/components/global-components/navbar";
import Footer from "@/components/global-components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pl">
      <body>
        {" "}
        <Providers>
          <Navbar />
          <div className="pt-28"> {children} </div>
          <Footer />
        </Providers>{" "}
      </body>
    </html>
  );
}

{
  /* <div id="portal"></div> */
}
